In [1]:
import numpy as np

In [11]:
a=np.array([1,23,2,3,4])

In [12]:
a.shape # returns the data in formate -> rows and colums

(5,)

In [13]:

b=np.array([[1,3,4,5],[2,3,4,5]])

In [16]:
b

array([[1, 3, 4, 5],
       [2, 3, 4, 5]])

In [18]:
b.shape #rows-> 2 columns-> 4

(2, 4)

In [24]:

b.dtype #-> data formate 

dtype('int32')

In [26]:
b.ndim # returns number roes 

2

In [27]:
print(type(b))


<class 'numpy.ndarray'>


In [29]:

np.arange(100) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
np.linspace(0,100,10) # IT WILL RETURN 10 ELEMENTS BETWEEN 0 to 100 

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [41]:

np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.eye(2) #identity matrix

array([[1., 0.],
       [0., 1.]])

In [49]:

np.full((4,4),10) 

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [50]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [51]:
x=np.arange(20)

In [56]:
print(x[0:10])


[0 1 2 3 4 5 6 7 8 9]


In [57]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])



In [61]:
z>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [62]:
z[z>2]

array([3, 4, 5, 6, 7, 8, 9])

In [65]:
a=np.array([[1,2,3,3,4],[1,2,3,4,5]])

In [67]:
a.T # Transpose 

array([[1, 1],
       [2, 2],
       [3, 3],
       [3, 4],
       [4, 5]])

In [75]:
b=np.array([[2,3,4,2,3],[3,2,3,4,4]])

In [76]:
np.vstack((a,b))

array([[1, 2, 3, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 2, 3],
       [3, 2, 3, 4, 4]])

In [77]:
x=np.arange(100)

In [80]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539,
        0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
        0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265,
       -0.26237485,  0.67022918,  0.98662759,  0.39592515, -0.55878905,
       -0.99975517, -0.521551  ,  0.43616476,  0.99287265,  0.63673801,
       -0.30481062, -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,
        0.82682868, -0.02655115, -0.85551998, -0.89792768, -0.11

In [85]:
b=np.array([[1,3],[2,3]])
np.linalg.det(b) # determint 

-2.9999999999999996

In [86]:
np.dot() #-> dot products 

SyntaxError: invalid syntax (<ipython-input-86-58b7a66bd678>, line 1)